version: '3.8'

services:
  mongodb:
    image: mongo:7-jammy
    restart: always
    networks:
      - app_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123456
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongodb:/data/db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  estoquevegetal:
    image: h1bertobarbosa/estoquevegetal-backend:latest
    networks:
      - app_network
    environment:
      NODE_ENV: production
    depends_on: # <-- ADICIONADO (Opcional, mas boa prática): Garante que o mongo tente iniciar primeiro.
      - mongodb
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1 # Evita que todas as instâncias reiniciem ao mesmo tempo
        delay: 10s
    ports:
      - 3001:3000

networks:
  app_network:
    driver: overlay

volumes:
  mongodb:
    driver: local
